### ISSUE TITLE
로또 구매 기능을 reusable workflow로 제공한다

### ISSUE THREAD

**Issue by viiviii** [viiviii/jubilant-train#73]
# 사용 예시

```
name: 🎁 로또 구매

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1-6'

jobs:
  purchase:
    uses: viiviii/jubilant-train/.github/workflows/purchase.yml@46fd432cefaf9733a34a8f52133fb622d48b6ae8
    secrets:
      id: ${{ secrets.LOTTERY_ACCOUNT_ID }}
      password: ${{ secrets.LOTTERY_ACCOUNT_PASSWORD }}
    with:
      amount: 1
```

<img width="825" alt="image" src="https://github.com/viiviii/jubilant-train/assets/75404713/d07e6b4a-4112-472f-b315-0f87310cf58e">
